.TH "HVIEW" "1" "2021-04-12" "" "hview"
.SH NAME
\fBhview-remove\fR - remove a directory from the database
.SH SYNOPSIS
.B hview remove [PATHS] [OPTIONS]
.SH DESCRIPTION
If you'd like to permanently exclude a directory from the database, see the
\fB_HVIEW_EXCLUDE_DIRS\fR environment variable in \fBhview\fR(1).
.SH OPTIONS
.TP
.B -h, --help
Print help information.
.SH REPORTING BUGS
For any issues, feature requests, or questions, please visit:
.sp
\fBhttps://github.com/ajeetdsouza/hview/issues\fR
.SH AUTHOR
Ajeet D'Souza \fB<98ajeet@gmail.com>\fR
