.TH "HVIEW" "1" "2021-04-12" "" "hview"
.SH NAME
\fBhview-init\fR - generate shell configuration for hview
.SH SYNOPSIS
.B hview init SHELL [OPTIONS]
.SH DESCRIPTION
To initialize hview on your shell:
.TP
.B bash
Add this to the \fBend\fR of your config file (usually \fB~/.bashrc\fR):
.sp
.nf
    \fBeval "$(hview init bash)"\fR
.fi
.TP
.B elvish
Add this to the \fBend\fR of your config file (usually \fB~/.elvish/rc.elv\fR):
.sp
.nf
    \fBeval $(hview init elvish | slurp)\fR
.fi
.sp
Note: hview only supports elvish v0.18.0 and above.
.TP
.B fish
Add this to the \fBend\fR of your config file (usually
\fB~/.config/fish/config.fish\fR):
.sp
.nf
    \fBhview init fish | source\fR
.fi
.TP
.B nushell
Add this to the \fBend\fR of your env file (find it by running
\fB$nu.env-path\fR in Nushell):
.sp
.nf
    \fBhview init nushell | save -f ~/.hview.nu\fR
.fi
.sp
Now, add this to the \fBend\fR of your config file (find it by running
\fB$nu.config-path\fR in Nushell):
.sp
.nf
    \fBsource ~/.hview.nu\fR
.fi
.sp
Note: hview only supports Nushell v0.106.0+.
.TP
.B powershell
Add this to the \fBend\fR of your config file (find it by running \fBecho
$profile\fR in PowerShell):
.sp
.nf
    \fBInvoke-Expression (& { (hview init powershell | Out-String) })\fR
.fi
.TP
.B tcsh
Add this to the \fBend\fR of your config file (usually \fB~/.tcshrc\fR):
.sp
.nf
    \fBhview init tcsh > ~/.hview.tcsh\fR
    \fBsource ~/.hview.tcsh\fR
.fi
.TP
.B xonsh
Add this to the \fBend\fR of your config file (usually \fB~/.xonshrc\fR):
.sp
.nf
    \fBexecx($(hview init xonsh), 'exec', __xonsh__.ctx, filename='hview')\fR
.fi
.TP
.B zsh
Add this to the \fBend\fR of your config file (usually \fB~/.zshrc\fR):
.sp
.nf
    \fBeval "$(hview init zsh)"\fR
.fi
.TP
.B any POSIX shell
.sp
Add this to the \fBend\fR of your config file:
.sp
.nf
    \fBeval "$(hview init posix --hook prompt)"\fR
.fi
.SH OPTIONS
.TP
.B --cmd
Changes the prefix of the \fBz\fR and \fBzi\fR commands.
.br
\fB--cmd j\fR would change the commands to (\fBj\fR, \fBji\fR).
.br
\fB--cmd cd\fR would replace the \fBcd\fR command (doesn't work on Nushell /
POSIX shells).
.TP
.B -h, --help
Print help information.
.TP
.B --hook HOOK
Changes how often hview increments a directory's score:
.TS
tab(|);
l l.
    \fBnone\fR|Never
    \fBprompt\fR|At every shell prompt
    \fBpwd\fR|Whenever the directory is changed
.TE
.TP
.B --no-cmd
Prevents hview from defining the \fBz\fR and \fBzi\fR commands. These functions
will still be available in your shell as \fB__hview_h\fR and \fB__hview_hi\fR,
should you choose to redefine them.
.SH REPORTING BUGS
For any issues, feature requests, or questions, please visit:
.sp
\fBhttps://github.com/ajeetdsouza/hview/issues\fR
.SH AUTHOR
Ajeet D'Souza \fB<98ajeet@gmail.com>\fR
